repos:

- repo: local
  hooks:
    - id: ruff-format
      name: ruff-format
      description: "Run 'ruff format' for extremely fast Python formatting"
      entry: uv run --dev ruff format
      pass_filenames: false
      always_run: true
      language: python
      types_or: [python, pyi, jupyter]
      args: []
      require_serial: true
      additional_dependencies: []

    - id: ruff
      name: ruff
      description: "Run 'ruff' for extremely fast Python linting"
      entry: uv run --dev ruff check
      pass_filenames: false
      always_run: true
      language: python
      types_or: [python, pyi, jupyter]
      args: []
      require_serial: true
      additional_dependencies: []

    - id: mdformat
      name: mdformat
      description: "Run 'mdformat' for Markdown formatting"
      entry: uv run --dev mdformat
      language: system
      types: [markdown]
