[project]
name = "ghoshell-moss"
version = "0.1.0"
description = "LLM-oriented operating system shell, providing interpreter for llm to control everything"
authors = [
    { name = "thirdgerb", email = "thirdgerb@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ghoshell-common>=0.4.0.dev1",
    "ghoshell-container>=0.3.0.dev1",
    "zmq>=0.0.0",
]

[project.optional-dependencies]
zmq = [
    "aiozmq>=1.0.0",
]
mcp = [
    "mcp[cli]>=1.17.0",
]
demo = [
    "live2d-py>=0.5.4",
    "pygame>=2.6.1",
    "pyside6>=6.10.0",
]
llm = [
    "litellm>=1.78.5",
]
agent = [
    "prompt-toolkit>=3.0.52",
    "rich>=14.2.0",
]

[tool.setuptools]
packages = [
    { include = "src" },
]


[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=1.1.0",
    "anyio>=4.10.0",
]

