web_list:
  - id: "moss-architecture-doc"
    url: "https://ycnrlabqki3v.feishu.cn/wiki/QCKUwAX7tiUs4GkJTkLcMeWqneh"
    description: "MOSS (模型可操作系统 - 流式代码解释器) 系统原理与应用综述"
  - id: "sphero-demo"
    url: "https://my.feishu.cn/docx/Vxttd4pAloIg9qxD5V8czIBtnag"
    description: |-
      2023 年5月左右实现的，基于大模型调用 sphero 球形可编程机器人。当时用的是 text-davinci-003 模型，自己实现解析
  - id: "ghostos-coding-demo"
    url: "https://my.feishu.cn/docx/JH5gdk5MFoPnpzxnBtecxmpWnab"
    description: |-
      关于 ghostos 项目在 AI 编程自迭代领域的探索，提供了各种示例，让 AI 大模型完全用代码理解一切，并且输出纯代码控制一切。
      其中包含用纯代码管理一个本地的代码库，使之可以分发。
  - id: "ghostos-repository"
    url: "https://github.com/GhostInShells/ghostos"
    description: |-
      GhostOS 代码仓库地址，是用来做 ghost in shells 架构思想探索的验证库。
  - id: "moss-article"
    url: "https://arxiv.org/abs/2409.16120"
    description: |-
      这是我们24年研究 AI 通过全代码驱动系统的相关论文预印版
  - id: "机械臂演示视频汇总"
    url: "https://ycnrlabqki3v.feishu.cn/wiki/FiOOwBKG0iSEONkGRKvcyDHOnaf"
    description: |-
      这里提供了我们 6dof jetarm 机械臂积累的展示视频
  - id: "20年语音交互视频展示视频"
    url: "https://www.bilibili.com/video/BV1tK4y1a75B/?share_source=copy_web&vd_source=d16eb4aa121a670f02fa576471d30a41"
    description: |-
      朱明 20年项目中，通过微信语音控制网页，通过网页的小视频做对话式视频的案例
  - id: "20年语音交互控制网页游戏视频"
    url: "https://www.bilibili.com/video/BV1tK4y1a75B/?share_source=copy_web&vd_source=d16eb4aa121a670f02fa576471d30a41&t=290"
    description: |-
      朱明 20年项目中，通过微信语音控制网页 “方向迷宫” 小游戏的视频，将网页游戏和微信进行了跨设备的同构。
  - id: "20年关于自然语言编程的视频"
    url: "https://www.bilibili.com/video/BV1tK4y1a75B/?share_source=copy_web&vd_source=d16eb4aa121a670f02fa576471d30a41&t=672"
    description: |-
      朱明 20年项目中，讨论到未来实现自然语言编程，对话式编程的设想。 
    
